Removed duplicate file moves

diff --git a/commands/move_imports b/commands/move_imports
--- a/commands/move_imports
+++ b/commands/move_imports
@@ -47,7 +47,6 @@ function move_imports::run () {
  
  local summary=$(get_summary "$img_log")
  check_error $summary
- echo $summary
 
  local images=$(get_imported_images "$img_log")
  check_error $images
@@ -129,6 +128,7 @@ get_imported_files(){
   local images=${3}
   # If it exists remove importsFiles so do not append to already existing file
   rm -f importedFiles.list 2> /tmp/om_imp
+  rm -f allImportedFiles.list 2> /tmp/om_imp
   # Parse group log file to get all associated/additional files
   local end=$(grep "#===" $grp_file | head -1)
   local start
@@ -137,8 +137,9 @@ get_imported_files(){
     start=$(grep "# Group: $img" $grp_file | head -1)
     escaped_start=$(printf '%s\n' "$start" | sed -e 's/[\/&]/\\&/g')
 	#Read all the lines between, and including, escaped_start and end; then delete first and last lines
-    sed -n "/${escaped_start}/,/${end}/ p" $grp_file | sed '1d' | sed '$d' >> importedFiles.list
+    sed -n "/${escaped_start}/,/${end}/ p" $grp_file | sed '1d' | sed '$d' >> allImportedFiles.list
   done
+  sort allImportedFiles.list | uniq > importedFiles.list
 }
 
 # Move imports data to imported folder
@@ -155,12 +156,13 @@ move_imports() {
       echo "ERROR: unable to create folder for $newFilename"
     fi
     mv "$filename" "$newFilename"
-    if [ $? -ne 0 ]; then
-      echo "ERROR: unable to move $filename to $newFilename"
+    ec=$?
+    if [ $ec -ne 0 ]; then
+      echo "ERROR: errorcode: $ec, unable to move $filename"
     fi
   done < importedFiles.list
   echo "Finished moving imported data"
-  rm importedFiles.list 2> /tmp/om_imp
+#  rm importedFiles.list 2> /tmp/om_imp
 }
 
 # Check directory exists
